server:
  port: 8083

spring:
  datasource:
    #    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/training?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

mybatis-plus:
  mapper-locations: classpath*:/META-INF/mapper/*.xml
  global-config:
    db-config:
      id-type: auto
#      tablePrefix: t_
  configuration:
    cache-enabled: false

logging:
  level:
    root: info
    cc:
      yuanspace:
        springboot:
          integration:
            mybatisplus: info

