POST http://localhost:8084/validator/api/group/validGroup2
Content-Type: application/json

{
  "num": 10
}

###
POST http://localhost:8084/validator/api/group/validGroup1
Content-Type: application/json

{
  "name": "ttt",
  "num": 11
}

###
POST http://localhost:8084/validator/api/group/validated
Content-Type: application/json

{

}

###
POST http://localhost:8084/validator/api/group/valid
Content-Type: application/json

{

}

###
